### PR TITLE
advanced drheader output

### PR DESCRIPTION
**Pull request by manuel-sommer**
This PR adds better output for the findings. 

- [x ] New feature (non-breaking change which adds functionality)
https://github.com/Santandersecurityresearch/DrHeader/issues/252

### CODE REVIEW

**Comment by manuel-sommer** [comment]
@javixeneize could you review this PR?

**Comment by manuel-sommer** [comment]
@javixeneize and @amias-channer could you please review this PR?

**Comment by manuel-sommer** [comment]
@javixeneize and @amias-channer could you please review this PR?

**Comment by danielcuthbert** [comment]
Apologies for the delay @manuel-sommer 
I'm reviewing now!

**Comment by manuel-sommer** [comment]
Hi @emilejq . When will you merge this PR to a new release?

**Comment by emilejq** [comment]
Hi @manuel-sommer,

I commented on the [issue](https://github.com/Santandersecurityresearch/DrHeader/issues/252) that you raised for this.

Expected values are already included in the output in the `expected` key, and the observed value is output in the `value` key. See the example below:

```json
{
    "rule": "Cache-Control",
    "message": "Value does not match security policy",
    "severity": "high",
    "value": "private, max-age=0",
    "expected": [
        "no-store",
        "max-age=0"
    ],
    "delimiter": ","
}
```

Likewise, avoid and anomalous values are already output in the `avoid` and `anomalies` keys respectively.

If you have found a specific scenario in which this is not the case, please let us know. Otherwise, this change is only duplicating information that is already included in the output

Thanks

**Comment by manuel-sommer** [comment]
Yes, you are right @emilejq. I am using a parser which only parses the "message" field, but this parser then should rather be fixed to also deal with the other fields in the json.

**Pull request closed without merging**
