### PR TITLE
CLI options

### PR DESCRIPTION
**Pull request by BodneyC**
# Proposed changes

The proposed changes are referenced in the five (at time of writing) commits, these address issue on the base specifically:

- #127 is updated by e33b71af3b18885eee32c0c3ad1eaa150cf51e22
- #125 is updated by 557c93dabe778412920b40c55fa2ee4b678a3924
- #126 is updated by:
  - d8e0f92b809a39b56100e8e5c58dcf651463ea3b, and
  - 9440a799753b1497d1d4c8e9e4561b04d729e269 for the default value

## Type of change

What types of changes do you want to introduce to DrHeader?

- [✓] Bugfix (non-breaking change which fixes an issue)

Please ensure your pull request adheres to the following guidelines:
- [✓] A Github Issue that explains the work.
  - Three linked below
- [✓] The changes are in a branch that is reasonably up to date
  - It's from master but currently merged to `develop` pick a branch at will
- [✓] You have the legal right to give us this code.
  - I certainly hope so
- [✓] You have adhered to the CoC
  - Assuming this is code of conduct, not conquer of completion, then I would assume, yes, but I didn't read it

## Link to the github issue 

- [this](https://github.com/Santandersecurityresearch/DrHeader/issues/127)
- [this](https://github.com/Santandersecurityresearch/DrHeader/issues/126)
- and, [this](https://github.com/Santandersecurityresearch/DrHeader/issues/125)

## Tests you have added 

- Nope

## Tests you have altered

- Nope

## Anything Else 

- Nope

Thanks for getting this far !

### CODE REVIEW

**Review by mrjonstrong — CHANGES_REQUESTED** [review]
@BodneyC Thanks so much for the PR, really great improvements. Can you please change sphinx to 3.0.4 on line 6 of requirements_dev.txt?
It should then pass the checks. 
Many thanks!

**Comment by BodneyC** [comment]
@mrjonstrong ,

Sphinx is updated to 3.2.0 and I've fixed a couple of bits in the documentation.

The one thing I will mention is that the images from the readme are not included in the resulting documentation because of pathing issues, however, I did not introduce this issue, it was already there.

**Review by mrjonstrong — APPROVED** [review]
Thanks for the updates @BodneyC they all look good.

**Comment by mrjonstrong** [comment]
Let's see if this works. 
This closes #125, #126, #127

**Pull request merged**
