### PR TITLE
Feature/junit report

### PR DESCRIPTION
**Pull request by jhbarrantes**
## Proposed changes

Adding a new feature to single scan that produces an xml file, Junit readable, with the result of the scan as test cases.

## Type of change

What types of changes do you want to introduce to DrHeader?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change 
- [x] Documentation Update
- [x] Test Update
- [ ] Rules Update 
- [ ] Other (please describe)

Please ensure your pull request adheres to the following guidelines:
- [x] A Github Issue that explains the work.
- [x] The changes are in a branch that is reasonably up to date
- [x] Tests are provided to reasonably cover new or altered functionality.
- [x] Documentation is provided for the new or altered functionality.
- [x] You have the legal right to give us this code.
- [x] You have adhered to the CoC

## Link to the github issue 

https://github.com/Santandersecurityresearch/DrHeader/issues/77

## Tests you have added 

test_cli_utils.py

## Tests you have altered

None

## Anything Else 
The new functionality is added by default with no option flag to single scan. Please consider if you'd like to add a flag to disable this feature.

Thanks for getting this far !

### CODE REVIEW

**Comment by jhbarrantes** [comment]
> I'm mainly happy with the proposed changes, however I think this feature would be best put under an optional flag. As well as the CI use cases, drheader is also intended to be used as a standalone tool for personal use, so in some cases these reports will not be required.

So let's say having a `--junit` flag, that enables this file output, otherwise won't produce the report? I'm happy with this, it can be quickly added.

**Comment by jhbarrantes** [comment]
New option `--junit` added to single scan, to enable the output of the Junit report, disabled by default.

**Comment by javixeneize** [comment]
Happy with it, but version should it still be 1.2.0? We have not released that version yet as we were waiting also for this change

**Comment by jhbarrantes** [comment]
I also updated README.md converting scan options into a table. Now it can be see at a glance.

**Comment by jhbarrantes** [comment]
> Happy with it, but version should it still be 1.2.0? We have not released that version yet as we were waiting also for this change

Happy to revert this back to 1.2.0. It was my first question actually. Please let me know your thoughts and I will amend this.

**Pull request merged**
